/*
 * Todo List API
 *
 * OpenAPI for TodoList RESTful API
 *
 * API version: 1.0
 * Contact: adhianamastur48@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {

	Success bool `json:"success,omitempty"`
}
