/*
 * Todo List API
 *
 * OpenAPI for TodoList RESTful API
 *
 * API version: 1.0
 * Contact: adhianamastur48@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateUpdateTodolist struct {

	Name string `json:"name"`

	Priority int32 `json:"priority"`

	Tags []string `json:"tags,omitempty"`
}
