/*
 * Todo List API
 *
 * OpenAPI for TodoList RESTful API
 *
 * API version: 1.0
 * Contact: adhianamastur48@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Todolist struct {

	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Priority int32 `json:"priority,omitempty"`

	Tags []string `json:"tags,omitempty"`
}
